// Bootcamp
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const GET_BOOTCAMPS = 'GET_BOOTCAMPS';
export const GET_BOOTCAMP = 'GET_BOOTCAMP';
export const CREATE_BOOTCAMP = 'CREATE_BOOTCAMP';
export const CREATE_BOOTCAMP_FAIL = 'CREATE_BOOTCAMP_FAIL';
export const DELETE_BOOTCAMP = 'DELETE_BOOTCAMP';
export const DELETE_BOOTCAMP_FAIL = 'DELETE_BOOTCAMP_FAIL';
export const UPDATE_BOOTCAMP = 'UPDATE_BOOTCAMP';
export const UPDATE_BOOTCAMP_FAIL = 'UPDATE_BOOTCAMP_FAIL';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';
export const GET_BOOTCAMPS_BY_DISTANCE = 'GET_BOOTCAMPS_BY_DISTANCE';

// Course
export const COURSE_LOADING = 'COURSE_LOADING';
export const GET_COURSES = 'GET_COURSES';
export const CREATE_COURSE = 'CREATE_COURSE';
export const CREATE_COURSE_FAIL = 'CREATE_COURSE_FAIL';
export const DELETE_COURSE = 'DELETE_COURSE';

// User
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

// Extra
export const LOADING = 'LOADING';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
